add-tr-language
justdeko/piley pull request #197
Opened 2024-05-30 17:17 UTC by mikropsoft

2024-06-03 19:05 UTC, justdeko commented
@mikropsoft thanks for adding support for turkish! Will be included within the next release 😄

2024-06-04 19:51 UTC, justdeko requested changes

2024-06-04 19:51 UTC, justdeko commented on app/src/main/res/values-tr/strings.xml
> +    <string name="set_base_url_setting_description">Yedeklemeleri yüklemek ve almak için uygulamanın bağlandığı temel istek URL'sini ayarlayın.</string>
this is missing an escape \ before the apostrophe, otherwise it looks good :)

2024-06-04 19:53 UTC, mikropsoft commented on app/src/main/res/values-tr/strings.xml
> +    <string name="set_base_url_setting_description">Yedeklemeleri yüklemek ve almak için uygulamanın bağlandığı temel istek URL'sini ayarlayın.</string>
Yes, I normally did this but I forgot :)

2024-06-05 07:36 UTC, mikropsoft commented on app/src/main/res/values-tr/strings.xml
> +    <string name="set_base_url_setting_description">Yedeklemeleri yüklemek ve almak için uygulamanın bağlandığı temel istek URL'sini ayarlayın.</string>
> this is missing an escape \ before the apostrophe, otherwise it looks good :)

I will fix it soon sir

2024-06-05 15:14 UTC, justdeko approved these changes

2024-06-05 15:15 UTC, merged